BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "STUDENT" (
	"EMAILADDRESS"	varchar(127),
	"L_NAME"	varchar(127),
	"F_NAME"	varchar(127),
	"CLASS"	varchar(9),
	PRIMARY KEY("EMAILADDRESS")
);
CREATE TABLE IF NOT EXISTS "CLUB" (
	"CLUB_NAME"	varchar(127),
	"PRESIDENT_EMAILADDRESS"	varchar(127),
	PRIMARY KEY("CLUB_NAME")
);
CREATE TABLE IF NOT EXISTS "PRODUIT" (
	"P_id"	integer,
	"NAME"	varchar(127),
	"PRICE"	integer,
	"P_CLUB"	varchar(127),
	PRIMARY KEY("P_id"),
	FOREIGN KEY("P_CLUB") REFERENCES "CLUB"("CLUB_NAME")
);
CREATE TABLE IF NOT EXISTS "ESTMEMBRE" (
	"CLUB_id"	varchar(127),
	"STUDENT_id"	varchar(127),
	FOREIGN KEY("CLUB_id") REFERENCES "CLUB"("CLUB_NAME"),
	FOREIGN KEY("STUDENT_id") REFERENCES "STUDENT"("EMAILADDRESS")
);
COMMIT;
